name: PG Driver Ubuntu

on: [push, pull_request]

jobs:
  build:
    name: PG Driver (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        deno: ["v1.7.1"]
      fail-fast: true    

    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_PASSWORD: Changeme1
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Setup Environment
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          echo ::set-env name=GH_ACTIONS::1
          echo ::set-env name=RUST_BACKTRACE::full

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.47.0
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-
      - name: Setup deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
      # Build
      - name: Build
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          cd rust-core && cd database && cd drivers && cd postgres && cargo build --release --locked --all-targets && cd ../../../../
          RUST_BACKTRACE=FULL MANDARINE_INTERNAL=true deno test -c tsconfig.json --reload --allow-all --unstable --fail-fast tests/db-tests/pg/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          files: |
            ./rust-core/database/drivers/postgres/target/release/libmandarine_postgres.so